name = "marked-og-worker"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "BROWSER"

[[r2_buckets]]
binding = "OG_SCREENSHOTS"
bucket_name = "marked-og-screenshots"
